version: 0.2

# env:
#   variables:
#     key: "value"
#     key: "value"

phases:
  # install:
  #   commands:
  #     - command
  #     - command

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git submodule init
      - git submodule update
      # Insert the PNG favicon into the header partial
      - sed -i 's|<title>{{ .Title }}</title>|<title>{{ .Title }}</title><link rel="shortcut icon" href="/favicon.png" type="image/x-icon">|' themes/dimension/layouts/partials/header.html
      # Insert the Google Analytics template code into the header HTML partial
      - sed -i 's|<!-- Scripts -->|<!-- Scripts -->\n\t\t\t{{ template "_internal/google_analytics_async.html" . }}|' themes/dimension/layouts/partials/header.html
      - grep template themes/dimension/layouts/partials/header.html

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      # Replace the GA_TRACKING_ID placeholder with the tracking ID from the environment variable
      - sed -i "s/{{GA_TRACKING_ID}}/$GA_TRACKING_ID/" config.toml
      - grep googleAnalytics config.toml
      - hugo --ignoreCache

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/public
      - aws s3 cp --recursive . s3://$TARGET_S3_BUCKET/website/

# artifacts:
#   files:
#     - location
#     - location
#   discard-paths: yes
#   base-directory: location
