baseurl = "https://www.flyingfortressit.ca"
title = "Flying Fortress IT"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
googleAnalytics = "{{GA_TRACKING_ID}}"
disableKinds = ["RSS"]

[params]
  description = '<!--[-->
  We are a team of experts specializing in public cloud technologies and IT security.<br/><br/>
  
  When it comes to security, we can help you or your organization improve its security posture through customized security awareness training, web site audits, and even penetration tests.<br/><br/>
  
  If you have been looking into moving part of your business to the cloud, or are not sure if it is the right fit for you, we can work with you to answer your questions and build solutions.<!--]-->'
  logoimage = "/images/logo.svg"
  copyright = "Flying Fortress IT 2017"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Flying Fortress IT"
